# Generated by Django 5.0 on 2024-01-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
